caipyra/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from dreams.views import dreams, thankyou

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', dreams),
    url(r'^thankyou/$', thankyou),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dreams/models.py
from __future__ import unicode_literals

from django.db import models


class Dreams(models.Model):
    counter = models.IntegerField()

dreams/forms.py
from django.forms import ModelForm
from .models import Dreams


class DreamsForm(ModelForm):
    class Meta:
        model = Dreams
        fields = ["counter"]

dreams/views.py
from django.shortcuts import render, redirect

from .forms import DreamsForm


def dreams(request):
    if request.session.get('voted'):
        return redirect("/thankyou/")

    form = DreamsForm(request.POST or None)
    
    if form.is_valid():
        form.save()
        request.session['voted'] = True
        return redirect("/thankyou/")

    context = {"form": form}
    return render(request, "dreams/index.html", context)


def thankyou(request):
    return render(request, "dreams/thankyou.html")

dreams/templates/dreams/index.html
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Caipyra 2016</title>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <img class="img-responsive" src="http://caipyra.python.org.br/img/caipyra_logo_2016.png" alt="Caipyra 2016">
                    <div class="intro-text">
                        <span class="skills color-yellow">O único evento de Python com Quentão e Paçoquinha!</span>
                        <h3>Quantos sonhos você realizou aqui no Caipyra?</h3>
                    </div>
                    <a href="#" class="btn btn-lg btn-buy btn-default">
                        Diz pra gente :)
                    </a>
                    <form method="POST" class="form-dreams">
                        {% csrf_token %}
                        <p>
                            <input id="id_counter" placeholder="1, 2, 4, 3000..." name="counter" type="number">
                        <p>
                        <p>
                            <button class="btn btn-lg btn-buy btn-default" type="submit">Enviar</button>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </header>
    <script src="{% static "js/app.js" %}"></script>
</body>
</html>

dreams/templates/dreams/thankyou.html
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Caipyra 2016</title>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- SO DE ZUA -->
                    <h1 style="color: white">Obrigadu!</h1>
                </div>
            </div>
        </div>
    </header>
</body>
</html>